language: c

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

env:
  - TARGET=
  - TARGET=debug

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew update &&
      brew install libtermkey &&
      brew install lua &&
      luarocks install lpeg;
    fi

script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      ./configure && make $TARGET;
    else
      make local && make clean && make $TARGET;
    fi
  - LD_LIBRARY_PATH="$(pwd)/dependency/install/usr/lib" make test
